Minor changes on zsh functions

diff --git a/prefix/airootfs/etc/zsh/functions/lock-screen b/prefix/airootfs/etc/zsh/functions/lock-screen
--- a/prefix/airootfs/etc/zsh/functions/lock-screen
+++ b/prefix/airootfs/etc/zsh/functions/lock-screen
@@ -1,13 +1,13 @@
 #!/usr/bin/env zsh 
 emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset
-need_installed swaylock grim ffplay || return $? # Check if command installed || exit
+need_installed swaylock grim paplay || return $? # Check if command installed || exit
 need_normal_user || return $? # Need normal user to run || exit
-killall -q swaylock grim ffplay # Clean up old process
 
+killall -q swaylock grim paplay # Clean up old process
 local temporary_file="/tmp/$(generate-random-string 20).jpg" # Create local variable for storing temporary_file name
 sleep 0.32 # Delay screenshot
 grim "$temporary_file" # Screenshot the whole screen and then output into temporary_file
-ffplay -nodisp -autoexit $(find /opt/craccken/sound/glitch -maxdepth 1 -type f -readable | shuf -n 1) &>/dev/null & # Play glitch sound
+paplay $(find /opt/craccken/sound/glitch -maxdepth 1 -type f -readable | shuf -n 1) &>/dev/null & # Play glitch sound
 edit_photo glitch "$temporary_file" "$temporary_file" & # Edit the output of screenshot with glitch effect and then output it into temporary_file
 wait # Wait edit_photo to complete, use the wait builtin to keep the script instance active until background jobs complete execution.
 
